### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by kabirjaipal** [saltyshiomix/react-ssr#42]
[](url)i am facing this error when i run the code

```js
techboy:express-jsx$ npm run dev

> express-jsx@1.0.0 dev
> node server.js

> Ready on http://localhost:3000
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/media/techboy/20121DFB121DD69E/Programing/coding/Codes/NPM PACKAGES/express-jsx/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/media/techboy/20121DFB121DD69E/Programing/coding/Codes/NPM PACKAGES/express-jsx/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/media/techboy/20121DFB121DD69E/Programing/coding/Codes/NPM PACKAGES/express-jsx/node_modules/webpack/lib/NormalModule.js:471:10)
    at /media/techboy/20121DFB121DD69E/Programing/coding/Codes/NPM PACKAGES/express-jsx/node_modules/webpack/lib/NormalModule.js:503:5
    at /media/techboy/20121DFB121DD69E/Programing/coding/Codes/NPM PACKAGES/express-jsx/node_modules/webpack/lib/NormalModule.js:358:12
    at /media/techboy/20121DFB121DD69E/Programing/coding/Codes/NPM PACKAGES/express-jsx/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/media/techboy/20121DFB121DD69E/Programing/coding/Codes/NPM PACKAGES/express-jsx/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Function.<anonymous> (/media/techboy/20121DFB121DD69E/Programing/coding/Codes/NPM PACKAGES/express-jsx/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.0
```

**Comment by adamzerner** [comment]
Does this solve your issue? https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

**Comment by kabirjaipal** [comment]
thanks

**Comment by adamzerner** [comment]
No problem! Would you like to close the issue if it was resolved?
